name: CI

on:
  push:
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run alejandra
        run: nix run github:kamadorueda/alejandra -- --check .
